name: Daily Commit

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Run update script
      run: python update.py

    - name: Commit changes
      env:
    	TOKEN: ${{ secrets.TARGET_PAT }}
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add data.txt
        git commit -m "Daily update"
	git push https://x-access-token:${TOKEN}@github.com/silentrk001/daily-activity-demo-app.git HEAD:main
